### ISSUE TITLE
Alternative to ADB Enhanced - Mobile Toolkit

### ISSUE THREAD

**Issue by luispinho** [igorwojda/android-ecosystem-cheat-sheet#12]
As an alternative/complement for ADB Enchanted, there's this project called "Mobile Toolkit" which has similar (and some more) features. It also supports both Android and iOS devices (even though this cheat sheet is only relative to Android). I use it for my development of apps and it works quite well, IMO. I believe it can be useful for more developers, let me know your opinion :D
You can check it here: https://github.com/IntergalacticPenguin/mobile-toolkit

**Comment by igorwojda** [comment]
Looks good - added.
Thanks for contribution @Pinho27
