### ISSUE TITLE
[Testing] Include Kaspresso

### ISSUE THREAD

**Issue by matzuk** [igorwojda/android-ecosystem-cheat-sheet#13]
Hi!

See [Kaspresso](https://github.com/KasperskyLab/Kaspresso).
Kaspresso is a great UiTest framework based on Espresso and UI Automator, and providing a wide set of such amazing features as:
1. 100% stability.
2. Increased speed of Espresso and UiAutomator command execution.
In case of UiAutomator, we get 10x acceleration for some commands!
3. Beautiful readability through human DSL.
4. Incredible mechanism of interceptors allowing you to catch all action and assertions in one place!
5. Understandable and full logging.
6. Ability to call ADB commands.
7. Philosophy how to write ui-tests and DSL providing this philosophy.
8. Light and convenient feature's screenshoting.
9. Etc.

**Comment by igorwojda** [comment]
Added thx, for contribution @matzuk
