### ISSUE TITLE
[Android Tools] Devtools

### ISSUE THREAD

**Issue by droidjavier** [igorwojda/android-ecosystem-cheat-sheet#16]
[Devtools](https://github.com/dhelleberg/android-scripts) is a script that allows you to toggle few of the developer options via command line.

Via devtools you can switch:

gfx (profile gpu rendering)

layout (show layout bounds)

overdraw

updates (show screen updates)

wifi (enable/disable wifi)

data (enable/disable mobile data)

**Comment by igorwojda** [comment]
It looks like most of the above features are covered by [adb-enhanced
](https://github.com/ashishb/adb-enhanced). In general `adb-enhanced` seems to be more matured project, so I would proffer to keep it in the ecosystem instead.

BTW I have opened PR for missing Wifi feature:
https://github.com/ashishb/adb-enhanced/issues/123

**Comment by droidjavier** [comment]
Oh I didn't know about that one.! 👍🏻👍🏻
