### ISSUE TITLE
[Android Tools] Material Cue

### ISSUE THREAD

**Issue by droidjavier** [igorwojda/android-ecosystem-cheat-sheet#17]
There's an app I use specially when designing layouts or views. Material Cue allows you overlay grids on the screen following material patterns. This could definitely be useful in certain cases.

https://play.google.com/store/apps/details?id=com.actinarium.materialcue

![device-2020-06-01-105935](https://user-images.githubusercontent.com/12748685/83393402-02f3c080-a3f7-11ea-9aef-84d1aa2d8e47.png)

![device-2020-06-01-110101](https://user-images.githubusercontent.com/12748685/83393504-30d90500-a3f7-11ea-96fb-67752998893e.png)

**Comment by igorwojda** [comment]
Added
Thanks for the multiple contributions @javierjmc

**Comment by droidjavier** [comment]
Glad to contribute. You compiled a great list!
