### ISSUE TITLE
board is not clearly visible

### ISSUE THREAD

**Issue by hafs-r** [igorwojda/android-ecosystem-cheat-sheet#8]

**Comment by Foenix00001** [comment]
Image is not detailed, very small to use somehow.

**Comment by igorwojda** [comment]
Image in the repo is only a preview. After clicking image on the main page you will bee redirected to `whimsical` board.

I have added a small readme with a link in the image folder.
https://github.com/igorwojda/android-ecosystem-cheat-sheet/blob/master/misc/image/board_readme.md

thx for contribution.
